/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Address (
  /*  */
  building: String,
  /*  */
  area: Option[String],
  /*  */
  region: Option[String],
  /*  */
  settlement: Option[String],
  /* `Dictionary SETTLEMENT_TYPE` */
  settlementType: Option[String],
  /* `Dictionary STREET_TYPE` */
  streetType: Option[String],
  /*  */
  street: Option[String],
  /*  */
  apartment: Option[String],
  /*  */
  zip: Option[String]
) extends ApiModel


