/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Auth (
  /* unique payment ID */
  md: Option[String],
  /* redirect url for *3-D Secure* verification */
  acsUrl: Option[String],
  /* payment authentication request */
  paReq: Option[String],
  /*  */
  terminalUrl: Option[String],
  /* card verification type */
  `type`: Option[String]
) extends ApiModel


