/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class CreateUserPageRequest (
  /* User card ID, MongoID */
  cardId: String,
  /* Fixed payment amount for page */
  amount: Option[Double],
  /* Page title */
  title: Option[String],
  /* Page description */
  description: Option[String],
  /* Will be page available for payments */
  isActive: Option[Boolean],
  /* Set page as default */
  isDefault: Option[Boolean],
  /*  */
  logo: Option[String],
  limits: Option[Limits133]
) extends ApiModel


