/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class CreateAnonymousPageRequest (
  /* Credit card number. Creates and adds card to page */
  cardNumber: String,
  /* Fixed payment amount for page */
  amount: Option[Double],
  /* Page title */
  title: Option[String],
  /* Page description */
  description: Option[String],
  /*  */
  logo: Option[String],
  limits: Option[Limits133]
) extends ApiModel


