/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class CreateDtekPageRequest (
  sender: DtekSender,
  /* each RES will have it's own merchant_id. */
  `resId: DTEK001`: String,
  /* Fixed payment amount for page. Can be edited by client */
  amount: Option[Double],
  /* Page title */
  title: Option[String],
  /* Page description. Payment purpose can be passed here. */
  description: Option[String],
  /*  */
  logo: Option[String],
  limits: Option[Limits133]
) extends ApiModel


