/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Limits (
  /* type Of limit (max payments count) */
  `type`: Option[String],
  /* value of max payments count */
  value: Option[Double],
  /* current payments count */
  current: Option[Double],
  /* is the limit exceeded */
  isExceeded: Option[Boolean]
) extends ApiModel


