/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class ResponsePagination (
  /* A limit on the number of objects to be returned, between 1 and 100. Default: 50. */
  limit: Option[Double],
  /* A cursor for use in pagination. An object ID that defines your position in the list. For example, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list. */
  startingAfter: Option[String],
  /* A cursor for use in pagination to fetch the previous page of the list. Equals to specified parameter *starting_after*. */
  endingBefore: Option[String],
  /* Total number of objects in collection. */
  count: Option[Double]
) extends ApiModel


