/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class SocialProfile (
  /* MongoId */
  id: Option[String],
  /* User Id */
  userId: Option[String],
  `type`: Option[Type],
  /* User first name from current social profile */
  firstName: Option[String],
  /* User last name from current social profile */
  lastName: Option[String],
  /* Link to avatar for current social profile */
  avatarUrl: Option[String]
) extends ApiModel


