/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class UpdateCurrentUserRequest (
  /* New user email */
  email: Option[String],
  /* New user phone */
  phone: Option[String],
  /* New user password Validation:1 digit, 1 alpha, length 6-32 */
  password: Option[String],
  /* User name */
  firstName: Option[String],
  /* User last name */
  lastName: Option[String],
  /* User new nickname */
  nickname: Option[String],
  /* User image. Can be url to image or base64 image data. */
  image: Option[String],
  locale: Option[Locale],
  emailSendFrequency: Option[EmailSendFrequency],
  /* User timezone, its need to sending account statements */
  timezone: Option[String],
  /* Checker if user and his pages active */
  active: Option[Boolean]
) extends ApiModel


