/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class User (
  /* MongoID */
  id: Option[String],
  /* User first name */
  firstName: Option[String],
  /* User last name */
  lastName: Option[String],
  /* Nickname пользователя */
  nickname: Option[String],
  /* User email */
  email: Option[String],
  /* User temporary email (email doesn't verified) */
  temporaryEmail: Option[String],
  /* User phone */
  phone: Option[String],
  /* User temporary phone (phone doensn't verified) */
  temporaryPhone: Option[String],
  /* User avatar */
  image: Option[String],
  /* User locale */
  locale: Option[String],
  /* User timezone */
  timezone: Option[String],
  emailSendFrequency: Option[EmailSendFrequency],
  /* Is user active */
  active: Option[Boolean],
  /* Is user blocked */
  isBlocked: Option[Boolean],
  /*  */
  pages: Option[Seq[PageShort]],
  /*  */
  cards: Option[Seq[CardShort]],
  /*  */
  webhooks: Option[Seq[Webhook]],
  /*  */
  socialProfiles: Option[Seq[SocialProfile]],
  /* User hash for intercom */
  intercomUserHash: Option[String]
) extends ApiModel


