/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class User11 (
  /* User nickname */
  nickname: Option[String],
  /* User first name */
  firstName: Option[String],
  /* User last name */
  lastName: Option[String],
  /* Link for page logo */
  image: Option[String],
  /* Checker if user is anonymous */
  isAnonymous: Option[Boolean]
) extends ApiModel


